#!/usr/bin/env sh

# Clean up Makevars
rm -f src/Makevars

# Clean up generated .relver
rm -f src/luajit/.relver

# Clean up luajit. Default value for $MAKE allows run from command line.
if [ `uname` = Darwin ]; then
  (export MACOSX_DEPLOYMENT_TARGET=10.8; cd src/luajit && ${MAKE:-make} clean)
else
  cd src/luajit && ${MAKE:-make} clean
fi
