#ifndef LUAJR_CONST_H
#define LUAJR_CONST_H

#define LUAJR_TOOLING_NONE 0
#define LUAJR_TOOLING_ALL 1
#define LUAJR_NO_ERROR_HANDLING 2
#define LUAJR_NO_PROFILE_COLLECT 4

#define LUAJR_DEBUG_MODE_OFF 0
#define LUAJR_DEBUG_MODE_ERROR 1
#define LUAJR_DEBUG_MODE_STEP 2

#define LUAJR_PROFILE_MODE_OFF 0
#define LUAJR_PROFILE_MODE_ON 1

#endif
